name: bachat_mart
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.20+25

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    rxdart: # https://pub.dev/packages/rxdart
    carousel_slider:
    provider:
    timer_builder:
    shared_preferences:
    parse_server_sdk:
    http:
    fluttertoast:

    flutter_sidebar:
    #sqflite: ^1.2.0
    #bottom_navy_bar: ^5.3.2
    intl:
    shimmer:
    google_sign_in:
    flutter_auth_buttons:
    paging:
    country_code_picker:
    #pin_code_text_field: ^1.5.1
    #gradient_widgets: ^0.5.2
#    gradient_app_bar:
    new_gradient_app_bar:
    sentry_flutter:
    google_maps_flutter:
    flutter_google_maps:
#    geolocator:
    geocoding: ^2.0.1
    firebase_crashlytics: ^2.5.1
#    flutter_inappwebview: ^5.3.2
    flutter_spinkit:
    share:
    launch_review:
    flutter_google_places:
    geocoder:
    material_floating_search_bar:
    search_map_place:
    location:
    flutter_facebook_login:
    firebase_messaging: ^11.2.4
    firebase_core :
    flutter_svg:
    #  cached_network_image: ^2.0.0
    cached_network_image:
    # app_settings:
    connectivity:
    url_launcher:
    flutter_html:
    flutter_webview_plugin:
    sign_in_apple: ^2.0.0
    scrollable_positioned_list:
    readmore:
    sms_autofill:
    getflutter:
    crisp: ^0.3.1
    introduction_screen:
    simple_tooltip:
    cupertino_icons:
    pinch_zoom_image_last:
    hive:
    hive_flutter:
    js:
    sizer:
    razorpay_flutter:
    #  google_maps: ^3.4.1
    flutter_google_places_web:
    google_maps_flutter_web:
    country_pickers:
    pin_code_text_field:
    percent_indicator:
    dotted_border:
    flutter_switch:
    radio_grouped_buttons:
    firebase_remote_config: #^0.3.0+3
    get_it:
    pub_semver:
    package_info:
    in_app_update:
    flutter_statusbarcolor_ns: ^0.4.0
    #ffi: ^1.0.0
    ffi:
    eventify:
    cashfree_pg: 2.0.5+25
    flutter_facebook_login_web:
    bloc: #^7.0.0
    flutter_login_facebook: ^1.2.0
    firebase_analytics:
    firebase_dynamic_links:
    collection:
#    paytm_allinonesdk:  #1.0.3 for solving conflict between Image_picker0.6.7+22 and paytm all in one sdk
    syncfusion_flutter_datepicker:
    permission_handler:
    custom_radio_grouped_button:
    device_apps:
    velocity_x:
    auto_size_text:
    font_awesome_flutter:
    image_picker:
    google_fonts:
    image_picker_web:
    page_transition:
    timeago:
    dotted_line:
    flutter_rating_bar:
    in_app_review:
    facebook_app_events: ^0.14.7
    go_router: ^3.0.1
    geolocator: ^8.0.3
    flutter_localizations:
        sdk: flutter

#    facebook_app_events:
#        path: customplugin/facebook_app_events-0.13.5


dev_dependencies:
    flutter_test:
        sdk: flutter
    splashscreen: ^1.2.0
    flutter_launcher_icons: "^0.7.3"
    hive_generator: ^0.8.2
    build_runner: ^1.10.6

dependency_overrides:
    flutter_svg: ^0.18.0

flutter_icons:
    android: true
    ios: true
    #image_path: "assets/images/icon1.png"
    image_path_android: assets/images/icon_android.png
    image_path_ios: assets/images/icon_ios.png
    adaptive_icon_background: assets/images/icon_background.png
    adaptive_icon_foreground: assets/images/icon_android.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
    assets:
        - assets/images/.

    fonts:
        - family: Lato
          fonts:
              - asset: assets/fonts/Lato-Bold.ttf
              - asset: assets/fonts/Lato-Regular.ttf

    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    # assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true